# Generated by Django 5.2.5 on 2025-09-01 05:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Etkinlik Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('start_time', models.CharField(max_length=50, verbose_name='Başlangıç Saati')),
                ('end_time', models.CharField(max_length=50, verbose_name='Bitiş Saati')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Konum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='projects.project', verbose_name='İlgili Proje')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Accepted', 'Katılıyorum'), ('Declined', 'Katılamıyorum'), ('Pending', 'Bekleniyor')], default='Pending', max_length=20, verbose_name='Katılım Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event', verbose_name='Etkinlik')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended_events', to='resources.resource', verbose_name='Katılımcı')),
            ],
            options={
                'verbose_name': 'Etkinlik Katılımı',
                'verbose_name_plural': 'Etkinlik Katılımları',
                'db_table': 'event_rsvps',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'resource')},
            },
        ),
    ]
