# Generated by Django 5.2.5 on 2025-09-01 07:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('ideas', '0002_alter_idea_author_alter_idea_budget_items_and_more'),
        ('projects', '0002_alter_project_created_at_alter_project_end_date_and_more'),
        ('resources', '0002_resource_bio_resource_current_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assignee',
            field=models.ForeignKey(blank=True, db_column='assigneeId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to='resources.resource', verbose_name='Atanan Kişi'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='event',
            name='completion_date',
            field=models.CharField(blank=True, db_column='completionDate', max_length=50, null=True, verbose_name='Tamamlanma Tarihi'),
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default='2025-01-01', max_length=50, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='event',
            name='dependencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, default=list, size=None, verbose_name='Bağımlılıklar'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.CharField(blank=True, db_column='endDate', max_length=50, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='event',
            name='estimated_hours',
            field=models.IntegerField(blank=True, db_column='estimatedHours', null=True, verbose_name='Tahmini Süre'),
        ),
        migrations.AddField(
            model_name='event',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None, verbose_name='Dosyalar'),
        ),
        migrations.AddField(
            model_name='event',
            name='idea',
            field=models.ForeignKey(blank=True, db_column='ideaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ideas.idea', verbose_name='İlgili Fikir'),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, default=list, size=None, verbose_name='Katılımcılar'),
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'Yüksek'), ('Medium', 'Orta'), ('Low', 'Düşük')], max_length=20, null=True, verbose_name='Öncelik'),
        ),
        migrations.AddField(
            model_name='event',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='İlerleme (%)'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hatırlatıcı'),
        ),
        migrations.AddField(
            model_name='event',
            name='reporter',
            field=models.ForeignKey(blank=True, db_column='reporterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_events', to='resources.resource', verbose_name='Rapor Eden'),
        ),
        migrations.AddField(
            model_name='event',
            name='spent_hours',
            field=models.IntegerField(blank=True, db_column='spentHours', null=True, verbose_name='Harcanan Süre'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.CharField(blank=True, db_column='startDate', max_length=50, null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('ToDo', 'Yapılacak'), ('InProgress', 'Devam Ediyor'), ('Done', 'Tamamlandı')], max_length=20, null=True, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Etiketler'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Appointment', 'Randevu'), ('Task', 'Görev'), ('Meeting', 'Toplantı'), ('Event', 'Etkinlik'), ('Note', 'Not')], default='Event', max_length=20, verbose_name='Etkinlik Tipi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.CharField(blank=True, db_column='endTime', max_length=50, null=True, verbose_name='Bitiş Saati'),
        ),
        migrations.AlterField(
            model_name='event',
            name='project',
            field=models.ForeignKey(blank=True, db_column='projectId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='projects.project', verbose_name='İlgili Proje'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(blank=True, db_column='startTime', max_length=50, null=True, verbose_name='Başlangıç Saati'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event', verbose_name='Etkinlik'),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='resource',
            field=models.ForeignKey(db_column='resourceId', on_delete=django.db.models.deletion.CASCADE, related_name='attended_events', to='resources.resource', verbose_name='Katılımcı'),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
    ]
