# Generated by Django 5.2.5 on 2025-09-01 07:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        ('resources', '0002_resource_bio_resource_current_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(db_column='authorId', on_delete=django.db.models.deletion.CASCADE, related_name='authored_ideas', to='resources.resource', verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='budget_items',
            field=models.JSONField(blank=True, db_column='budgetItems', null=True, verbose_name='Bütçe Kalemleri'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='creation_date',
            field=models.CharField(blank=True, db_column='creationDate', max_length=50, null=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='critical_milestones',
            field=models.TextField(blank=True, db_column='criticalMilestones', null=True, verbose_name='Kritik Kilometre Taşları'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='estimated_duration',
            field=models.CharField(blank=True, db_column='estimatedDuration', max_length=100, null=True, verbose_name='Tahmini Süre'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='expected_cost_savings',
            field=models.FloatField(blank=True, db_column='expectedCostSavings', null=True, verbose_name='Beklenen Maliyet Tasarrufu'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='expected_revenue_increase',
            field=models.FloatField(blank=True, db_column='expectedRevenueIncrease', null=True, verbose_name='Beklenen Gelir Artışı'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='expected_roi',
            field=models.FloatField(blank=True, db_column='expectedROI', null=True, verbose_name='Beklenen ROI'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='funding_sources',
            field=models.TextField(blank=True, db_column='fundingSources', null=True, verbose_name='Finansman Kaynakları'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='potential_team',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, db_column='potentialTeam', default=list, size=None, verbose_name='Potansiyel Takım'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='problem_frequency',
            field=models.CharField(blank=True, db_column='problemFrequency', max_length=50, null=True, verbose_name='Problem Sıklığı'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='problem_type',
            field=models.CharField(blank=True, db_column='problemType', max_length=50, null=True, verbose_name='Problem Tipi'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='project_leader',
            field=models.ForeignKey(blank=True, db_column='projectLeaderId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_ideas', to='resources.resource', verbose_name='Proje Lideri'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='related_departments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, db_column='relatedDepartments', default=list, size=None, verbose_name='İlgili Departmanlar'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='revenue_sources',
            field=models.TextField(blank=True, db_column='revenueSources', null=True, verbose_name='Gelir Kaynakları'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='risk_level',
            field=models.CharField(blank=True, db_column='riskLevel', max_length=20, null=True, verbose_name='Risk Seviyesi'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='success_criteria',
            field=models.TextField(blank=True, db_column='successCriteria', null=True, verbose_name='Başarı Kriterleri'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='swot_opportunities',
            field=models.TextField(blank=True, db_column='swotOpportunities', null=True, verbose_name='Fırsatlar'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='swot_strengths',
            field=models.TextField(blank=True, db_column='swotStrengths', null=True, verbose_name='Güçlü Yönler'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='swot_threats',
            field=models.TextField(blank=True, db_column='swotThreats', null=True, verbose_name='Tehditler'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='swot_weaknesses',
            field=models.TextField(blank=True, db_column='swotWeaknesses', null=True, verbose_name='Zayıf Yönler'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='target_audience',
            field=models.TextField(blank=True, db_column='targetAudience', null=True, verbose_name='Hedef Kitle'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='timeline_phases',
            field=models.JSONField(blank=True, db_column='timelinePhases', null=True, verbose_name='Zaman Çizelgesi Aşamaları'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='total_budget',
            field=models.FloatField(blank=True, db_column='totalBudget', null=True, verbose_name='Toplam Bütçe'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='idea',
            field=models.ForeignKey(db_column='ideaId', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ideas.idea', verbose_name='Fikir'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='resource',
            field=models.ForeignKey(db_column='resourceId', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='resources.resource', verbose_name='Oy Veren'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
    ]
