# Generated by Django 5.2.5 on 2025-09-01 05:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-posta')),
                ('role', models.CharField(choices=[('Superadmin', 'Süper Admin'), ('Admin', 'Admin'), ('Manager', 'Yönetici'), ('TeamLead', 'Ekip Lideri'), ('Member', 'Ekip Üyesi')], default='Member', max_length=20, verbose_name='Rol')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departman')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('start_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='İşe Başlama Tarihi')),
                ('avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='Profil Fotoğrafı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kaynak',
                'verbose_name_plural': 'Kaynaklar',
                'db_table': 'resources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Departman Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resources.department', verbose_name='Üst Departman')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='resources.resource', verbose_name='Departman Müdürü')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
    ]
