# Generated by Django 5.2.5 on 2025-09-01 07:07

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biyografi'),
        ),
        migrations.AddField(
            model_name='resource',
            name='current_load',
            field=models.IntegerField(db_column='currentLoad', default=0, verbose_name='Mevcut Yük (%)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='department_id',
            field=models.CharField(db_column='departmentId', default='', max_length=36, verbose_name='Departman ID'),
        ),
        migrations.AddField(
            model_name='resource',
            name='earned_badges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, db_column='earnedBadges', default=list, size=None, verbose_name='Kazanılan Rozetler'),
        ),
        migrations.AddField(
            model_name='resource',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FullTime', 'Tam Zamanlı'), ('PartTime', 'Yarı Zamanlı'), ('Contractor', 'Sözleşmeli'), ('Intern', 'Stajyer')], db_column='employmentType', max_length=20, null=True, verbose_name='İstihdam Tipi'),
        ),
        migrations.AddField(
            model_name='resource',
            name='initials',
            field=models.CharField(default='', max_length=10, verbose_name='Baş Harfler'),
        ),
        migrations.AddField(
            model_name='resource',
            name='manager_id',
            field=models.CharField(blank=True, db_column='managerId', max_length=36, null=True, verbose_name='Yönetici ID'),
        ),
        migrations.AddField(
            model_name='resource',
            name='position',
            field=models.CharField(default='', max_length=255, verbose_name='Pozisyon'),
        ),
        migrations.AddField(
            model_name='resource',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Yetenekler'),
        ),
        migrations.AddField(
            model_name='resource',
            name='weekly_hours',
            field=models.IntegerField(db_column='weeklyHours', default=40, verbose_name='Haftalık Çalışma Saati'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='managerId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='resources.resource', verbose_name='Departman Müdürü'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parentId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resources.department', verbose_name='Üst Departman'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='start_date',
            field=models.CharField(blank=True, db_column='startDate', max_length=50, null=True, verbose_name='İşe Başlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
    ]
