# Generated by Django 5.2.5 on 2025-09-01 05:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='İçerik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('BugReport', 'Hata Bildirimi'), ('FeatureRequest', 'Özellik Talebi'), ('General', 'Genel Yorum')], max_length=20, verbose_name='Kategori')),
                ('status', models.CharField(choices=[('Submitted', 'Gönderildi'), ('InProgress', 'İnceleniyor'), ('Resolved', 'Çözüldü'), ('Closed', 'Kapatıldı')], default='Submitted', max_length=20, verbose_name='Durum')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geri Bildirim',
                'verbose_name_plural': 'Geri Bildirimler',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='Fatura Numarası')),
                ('amount', models.FloatField(verbose_name='Tutar')),
                ('status', models.CharField(choices=[('Unpaid', 'Ödenmedi'), ('Paid', 'Ödendi')], default='Unpaid', max_length=20, verbose_name='Durum')),
                ('due_date', models.CharField(max_length=50, verbose_name='Vade Tarihi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Talep Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('amount', models.FloatField(verbose_name='Tutar')),
                ('status', models.CharField(choices=[('Pending', 'Onay Bekliyor'), ('Approved', 'Onaylandı'), ('Rejected', 'Reddedildi')], default='Pending', max_length=20, verbose_name='Durum')),
                ('requester_id', models.CharField(max_length=36, verbose_name='Talep Eden ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Satın Alma Talebi',
                'verbose_name_plural': 'Satın Alma Talepleri',
                'db_table': 'purchase_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
