# Generated by Django 5.2.5 on 2025-09-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        ('ideas', '0001_initial'),
        ('projects', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ideas.idea', verbose_name='İlgili Fikir'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='İlgili Proje'),
        ),
        migrations.AddField(
            model_name='comment',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resources.resource', verbose_name='Yorum Yapan'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.task', verbose_name='İlgili Görev'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='resources.resource', verbose_name='Geri Bildirim Veren'),
        ),
    ]
