# Generated by Django 5.2.5 on 2025-09-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
        ('events', '0002_event_assignee_event_category_event_completion_date_and_more'),
        ('ideas', '0002_alter_idea_author_alter_idea_budget_items_and_more'),
        ('projects', '0002_alter_project_created_at_alter_project_end_date_and_more'),
        ('resources', '0002_resource_bio_resource_current_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(blank=True, db_column='eventId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event', verbose_name='İlgili Etkinlik'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='idea',
            field=models.ForeignKey(blank=True, db_column='ideaId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ideas.idea', verbose_name='İlgili Fikir'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(blank=True, db_column='projectId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='İlgili Proje'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='resource',
            field=models.ForeignKey(db_column='resourceId', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resources.resource', verbose_name='Yorum Yapan'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, db_column='taskId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.task', verbose_name='İlgili Görev'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='resource',
            field=models.ForeignKey(db_column='resourceId', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='resources.resource', verbose_name='Geri Bildirim Veren'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(db_column='dueDate', max_length=50, verbose_name='Vade Tarihi'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_column='invoiceNumber', max_length=100, unique=True, verbose_name='Fatura Numarası'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requester_id',
            field=models.CharField(db_column='requesterId', max_length=36, verbose_name='Talep Eden ID'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
    ]
