# Generated by Django 5.2.5 on 2025-09-01 05:43

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Proje Kodu')),
                ('status', models.CharField(choices=[('Active', 'Aktif'), ('Planning', 'Planlama'), ('Completed', 'Tamamlandı')], default='Planning', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('High', 'Yüksek'), ('Medium', 'Orta'), ('Low', 'Düşük')], default='Medium', max_length=20, verbose_name='Öncelik')),
                ('start_date', models.CharField(max_length=50, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.CharField(max_length=50, verbose_name='Bitiş Tarihi')),
                ('progress', models.IntegerField(default=0, verbose_name='İlerleme (%)')),
                ('team', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, default=list, size=None, verbose_name='Takım Üyeleri')),
                ('budget', models.FloatField(verbose_name='Bütçe')),
                ('color', models.CharField(max_length=20, verbose_name='Renk')),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None, verbose_name='Dosyalar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to='resources.resource', verbose_name='Proje Müdürü')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Görev Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('ToDo', 'Yapılacak'), ('InProgress', 'Devam Ediyor'), ('Done', 'Tamamlandı')], default='ToDo', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('High', 'Yüksek'), ('Medium', 'Orta'), ('Low', 'Düşük')], default='Medium', max_length=20, verbose_name='Öncelik')),
                ('start_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='resources.resource', verbose_name='Atanan Kişi')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Proje')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tasks', to='resources.resource', verbose_name='Rapor Eden')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
