# Generated by Django 5.2.5 on 2025-09-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('resources', '0002_resource_bio_resource_current_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.CharField(db_column='endDate', max_length=50, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(db_column='managerId', on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to='resources.resource', verbose_name='Proje Müdürü'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.CharField(db_column='startDate', max_length=50, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(db_column='assigneeId', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='resources.resource', verbose_name='Atanan Kişi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.CharField(blank=True, db_column='endDate', max_length=50, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reporter',
            field=models.ForeignKey(blank=True, db_column='reporterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tasks', to='resources.resource', verbose_name='Rapor Eden'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.CharField(blank=True, db_column='startDate', max_length=50, null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
    ]
